name: Build & Test

on:
  push:
    branches: [master, next, "*.x", "*.*.x"]
  pull_request:
    branches: [master, next, "*.x", "*.*.x"]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.6.0, 14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Fix package.json (Node 14.6.0)
        if: ${{ startsWith(matrix.node-version, '14.') }}
        run: |
          npx json -I -f package.json -e "this.scripts.prepare=this.scripts.build"
          npm uninstall semantic-release
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test -- --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lsndr/weak-identity-map